### ISSUE TITLE
std-*.aiml errors

### ISSUE THREAD

**Issue by jrwarwick** [Calysto/aiml#4]
It is really great to have a nicer, cleaner set of base AIML files to start with, thanks for that.
I found what I believe to be a few errors in the standard aiml collection. Is this the "upstream" location for those? Or should I file issues and pull requests elsewhere and then they get copied into here?

example: in std-personality.aiml

```
<li>I require only <bot name="favoritefood"/>.</li>
<li>My favorite movie is <favoritemovie/>.  Have you seen <set name="it"><set name="topic">
<favoritemovie/> </set></set>?</li>
<li>My favorite song is <favoritesong/>.  Do you know <set name="it"><set name="topic">
<favoritesong/> </set></set>?</li>
</ul>
</template>
```
I think the tags for favoritemovie and favoritesong should be more <bot> tags. Like so:

```
<li>I require only <bot name="favoritefood"/>.</li>
<li>My favorite movie is <bot name="favoritemovie"/>.  Have you seen <set name="it"><set name="topic">
<bot name="favoritemovie"/> </set></set>?</li>
<li>My favorite song is *<bot name="favoritesong"/>.  Do you know <set name="it"><set name="topic">
<bot name="favoritesong"/> </set></set>?</li>
</ul>
</template>
```

**Comment by dsblank** [comment]
Can you file an issue? Thanks!

**Comment by jrwarwick** [comment]
I found a few more things I think of as flaws, details following. Should I file one PR for all of these as "standard AIML quality improvements"? Or do you want one PR per type of correction?

1.
for_fun tag appears to have been the bot's list of hobbies, to give it some appearance of personality. They could be replaced with more bot global property tags (with name attribute of "hobby", perhaps, or is there a more universal english term for the same? "amateur pursuits"?).

2.
"em", "p", "br", and "a" html tags are scattered in the std aiml files. Again from aiml.foundation doc:
"In the early days of AIML, when most bots were displayed on web pages, we allowed the AIML <template> to contain a mix of HTML and AIML tags. For the bot to display a hyperlink of image, or to stylize the response, the botmaster could include HTML tags like <a>, <img>, or <b> as part of the bot's reply.
Unfortunately instant messaging platforms lack a standard, common language like HTML to implement such a commonplace text decoration. For this reason AIML 2.1 specifies Rich Media tags..." 
My inclination is to remove all the standard HTML tags (that aren't mentioned explicitly in the supported tags document).

3.
Several http URLs are embedded in the std AIML content. Several of them are no longer valid URLs. Updated versions where possible, otherwise delete.

**Comment by dsblank** [comment]
Just one PR is fine, or however you prefer to work. Thank you!

**Comment by dsblank** [comment]
Thanks so much!
