### ISSUE TITLE
Windows + Python 3.8 breaks the package

### ISSUE THREAD

**Issue by rvencu** [Calysto/aiml#9]
Python 3.8 removed time.clock() so there is need for a workaround to overcome this error:

AttributeError: module 'time' has no attribute 'clock'

**Comment by rvencu** [comment]
Oh, I just saw you changed this already but pip install keeps pushing a version without this change (0.9.2)

**Comment by rvencu** [comment]
solved with
```
pip uninstall aiml
python -m pip install git+https://github.com/Calysto/aiml
```

**Comment by dsblank** [comment]
Thanks for the note. Yes, looks like we need to create a new pip install. We're going through some re-org. More on that soon.
